#!/bin/sh
if [ -z "$1" ]; then
  echo "Supports: start, stop, restart, status, log"
  exit 1
fi

SOSSBOX=$HOME/bin/sossdata

PWD=`pwd`
site=`basename $PWD`

echo "sossctl $*"
if [ "$1" = "start" ]; then
  echo "Starting sossdata instance for '$site' ..."
  $SOSSBOX
elif [ "$1" = "stop" ]; then
  if [ -s sossdata.pid ]; then
    kill -TERM --pid `cat sossdata.pid`
    echo "Sent terminate to sossdata instance for '$site' ..."
  else
    echo "sossdata is not running in `pwd`"
  fi
elif [ "$1" = "restart" ]; then
  echo "Restarting sossdata instance for '$site' ..."
  kill -TERM --pid `cat sossdata.pid` && $SOSSBOX
elif [ "$1" = "status" ]; then
  # ps --pid `cat sossdata.pid`
  systemctl status $site
elif [ "$1" = "log" ]; then
  journalctl -u $site -n 20
fi
